version: "3.9"
services:
  app: # our ads registration service
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: node-app-container
    environment:
      DB_USER: "root"
      DB_PASS: "mauFJcuf5dhRMQrjj"
      DB_HOST: "mysql-container"
      DB_PORT: "3306"
      DB_NAME: "ads"
      ADMIN_NAME: "admin"
      ADMIN_PASS: "MTIzNDU=" # password is 12345
      JWT_KEY: "88512%sup%*119"
      HTTP_PORT: "8080"
    volumes:
      - images:/app/images
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  mysql: # mysql database
    container_name: mysql-container
    hostname: mysql-container
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: on-failure
    environment:
      - MYSQL_DATABASE=ads
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  images:
    driver: local
  db:
    driver: local
